management:
  endpoint:
    health:
      show-details: always
    
server:
  port: 8000
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${eureka_servers:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true          

logging:
  level:
    root: info
    path: ./logs/
    
spring:
  application:
    name: bank-client