# eureka-server
spring:
  application:
    name: eureka-server
    
server:
  port: 8761

eureka:
  server:
    renewalPercentThreshold: 0.3
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/